{{- if and .Values.consentSelfservice.enabled .Values.consentSelfservice.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "openbanking.consentSelfservice.fullname" . }}
{{- $servicePort := .Values.consentSelfservice.service.servicePort -}}
{{- $extraPaths := .Values.consentSelfservice.ingress.extraPaths -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
{{- if .Values.consentSelfservice.ingress.annotations }}
  annotations:
{{ toYaml .Values.consentSelfservice.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "openbanking.consentSelfservice.labels" . | nindent 4 }}
{{- range $key, $value := .Values.consentSelfservice.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
  name: {{ template "openbanking.consentSelfservice.fullname" . }}
{{ include "openbanking.namespace" . | indent 2 }}
spec:
  rules:
  {{- range .Values.consentSelfservice.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: /{{ rest $url | join "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
  {{- end -}}
{{- if .Values.consentSelfservice.ingress.tls }}
  tls:
{{ toYaml .Values.consentSelfservice.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
