{{- if .Values.clientCredentials.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "standalone-authorizer.clientCredentialsName" . }}
  labels:
    {{- include "standalone-authorizer.labels" . | nindent 4 }}
data:
  clientID: {{ .Values.clientCredentials.clientID | b64enc }}
  clientSecret: {{ .Values.clientCredentials.clientSecret | b64enc }}
{{- end }}
