apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigee-authorizer.fullname" . }}
  labels:
    {{- include "apigee-authorizer.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.data }}
  {{- if $key | regexMatch ".*\\.ya?ml$" }}
  {{ $key }}: |
    {{- toYaml $value | default "{}" | indent 4 }}
  {{- else }}
  {{ $key }}: {{ toYaml $value | indent 4 }}
  {{- end }}
{{- end -}}
