{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acp.serviceAccountName" . }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.fission.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "acp.serviceAccountName" . }}
  namespace: {{ .Values.fission.namespace }}
rules:
  - apiGroups:
      - "fission.io"
    resources:
      - "packages"
      - "functions"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acp.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acp.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acp.serviceAccountName" . }}
{{- end }}
