{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acp.serviceAccountName" . }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if or (eq .Values.faas.enabled true) (eq .Values.fission.enabled true) }}
{{- if or (eq .Values.faas.provider "fission") (eq .Values.faas.provider "hybrid") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acp.serviceAccountName" . }}
rules:
  - apiGroups:
      - "fission.io"
    resources:
      - "packages"
      - "functions"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acp.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acp.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acp.serviceAccountName" . }}
{{- end }}
{{- end }}
